import type {
  AgentRecord,
  Approval,
  AuditLogEntry,
  Conversation,
  DocumentSource,
  Operation,
  PropertyRecord,
} from "./types";

export const properties: PropertyRecord[] = [
  {
    id: "p1",
    address: "71 Cantonment Close #12-184",
    units: ["#12-184", "#12-185"],
    owner: "Maya Chen",
    tenants: ["Priya Menon", "Daniel Ho"],
    openMaintenance: 2,
    leaseStatus: "Expires in 52 days",
    pendingInvoices: 1,
    recentActivity: "ContractAgent queued renewal scheduling for CommsAgent.",
  },
  {
    id: "p2",
    address: "18 Jervois Road #06-03",
    units: ["#06-03", "#06-04"],
    owner: "Adrian Lim",
    tenants: ["Nora Tan", "Hafiz Rahman"],
    openMaintenance: 1,
    leaseStatus: "Active until Sep 2027",
    pendingInvoices: 2,
    recentActivity: "InvoiceAgent submitted receipt claim for review.",
  },
  {
    id: "p3",
    address: "9 Tanjong Rhu Road #21-10",
    units: ["#21-10", "#21-11"],
    owner: "Sophia Ong",
    tenants: ["Mei Wong"],
    openMaintenance: 0,
    leaseStatus: "Renewal meeting scheduled",
    pendingInvoices: 0,
    recentActivity: "CommsAgent created owner calendar invitation.",
  },
];

export const contacts = {
  tenants: ["Priya Menon", "Daniel Ho", "Nora Tan", "Hafiz Rahman", "Mei Wong"],
  owners: ["Maya Chen", "Adrian Lim", "Sophia Ong"],
  contractors: ["CoolAir Services", "BrightPlumb", "Urban Electric", "LiftCare SG", "Prime Cleaning"],
};

export const operations: Operation[] = [
  {
    id: "op-1001",
    agent: "CommsAgent",
    workflowType: "schedule_lease_renewal_meeting",
    property: "71 Cantonment Close #12-184",
    person: "Maya Chen",
    timestamp: "Today, 10:42",
    status: "Running",
    confidence: 91,
    proposedAction: "Collect owner and manager availability, then create Google Calendar event.",
    approvalRequired: false,
    handoffChain: ["OrchestratorAgent", "ContractAgent", "CommsAgent"],
    evidence: ["Lease expiry task jx76k81...", "Lease PDF extraction confidence 100%", "Owner email and manager calendar preference"],
    related: ["Lease: 2026-04-01 to 2027-03-31", "Conversation: WhatsApp with owner", "Calendar draft"],
    audit: ["ContractAgent created renewal task", "CommsAgent claimed queued task", "Availability prompt prepared"],
  },
  {
    id: "op-1002",
    agent: "MaintenanceAgent",
    workflowType: "Maintenance",
    property: "18 Jervois Road #06-03",
    person: "Nora Tan",
    timestamp: "Today, 09:55",
    status: "Awaiting approval",
    confidence: 86,
    proposedAction: "Approve vendor scheduling for leaking AC inspection.",
    approvalRequired: true,
    handoffChain: ["OrchestratorAgent", "MaintenanceAgent", "CommsAgent", "Human Approval"],
    evidence: ["Tenant photo", "Approved vendor list", "Prior AC service history"],
    related: ["Task: AC leak", "Vendor: CoolAir Services"],
    audit: ["Vendor matched", "Tenant availability received", "Approval requested"],
  },
  {
    id: "op-1003",
    agent: "ContractAgent",
    workflowType: "Lease extraction",
    property: "71 Cantonment Close #12-184",
    person: "Priya Menon",
    timestamp: "Yesterday, 17:18",
    status: "Completed",
    confidence: 100,
    proposedAction: "Handoff completed to CommsAgent for renewal meeting.",
    approvalRequired: false,
    handoffChain: ["OrchestratorAgent", "ContractAgent", "CommsAgent"],
    evidence: ["sample_fake_lease_agreement_ocr_test.pdf", "Extracted lease dates", "Demo seeded property"],
    related: ["Lease record jd7cch...", "Agent task jx76k81..."],
    audit: ["Lease PDF processed", "Expiry detected within 60 days", "Comms task queued"],
  },
  {
    id: "op-1004",
    agent: "InvoiceAgent",
    workflowType: "Invoice claim",
    property: "18 Jervois Road #06-04",
    person: "Hafiz Rahman",
    timestamp: "Yesterday, 15:32",
    status: "Human review required",
    confidence: 62,
    proposedAction: "Review low OCR confidence before reimbursement approval.",
    approvalRequired: true,
    handoffChain: ["OrchestratorAgent", "InvoiceAgent", "Human Approval"],
    evidence: ["receipt_blur_041.png", "Amount extracted: SGD 284.60", "OCR confidence low"],
    related: ["Invoice claim", "Tenant conversation"],
    audit: ["Receipt uploaded", "OCR confidence low", "Approval created"],
  },
  {
    id: "op-1005",
    agent: "CommsAgent",
    workflowType: "Owner communication",
    property: "9 Tanjong Rhu Road #21-10",
    person: "Sophia Ong",
    timestamp: "Yesterday, 13:10",
    status: "Ready to send",
    confidence: 94,
    proposedAction: "Send renewal meeting confirmation with calendar link.",
    approvalRequired: false,
    handoffChain: ["ContractAgent", "CommsAgent"],
    evidence: ["Owner availability reply", "Manager calendar slot", "Lease expiry workflow"],
    related: ["Email draft", "Calendar event"],
    audit: ["Availability collected", "Calendar event created", "Message drafted"],
  },
  {
    id: "op-1006",
    agent: "OrchestratorAgent",
    workflowType: "Handoff",
    property: "71 Cantonment Close #12-185",
    person: "Daniel Ho",
    timestamp: "Mon, 16:44",
    status: "Completed",
    confidence: 89,
    proposedAction: "Routed tenant reimbursement message to InvoiceAgent.",
    approvalRequired: false,
    handoffChain: ["OrchestratorAgent", "InvoiceAgent"],
    evidence: ["Inbound WhatsApp", "Attached receipt", "Tenant-property match"],
    related: ["Conversation c-206", "Invoice draft"],
    audit: ["Intent classified", "Context loaded", "Handoff completed"],
  },
  {
    id: "op-1007",
    agent: "MaintenanceAgent",
    workflowType: "Vendor matching",
    property: "18 Jervois Road #06-03",
    person: "CoolAir Services",
    timestamp: "Mon, 11:24",
    status: "SLA at risk",
    confidence: 78,
    proposedAction: "Escalate if vendor does not reply by 18:00.",
    approvalRequired: false,
    handoffChain: ["OrchestratorAgent", "MaintenanceAgent", "CommsAgent"],
    evidence: ["Open maintenance SLA", "Vendor response pending", "Tenant issue marked high priority"],
    related: ["Maintenance task", "Vendor conversation"],
    audit: ["Vendor contacted", "Reminder queued"],
  },
  {
    id: "op-1008",
    agent: "InvoiceAgent",
    workflowType: "Reimbursement",
    property: "71 Cantonment Close #12-184",
    person: "Priya Menon",
    timestamp: "Fri, 14:06",
    status: "Completed",
    confidence: 98,
    proposedAction: "Tenant confirmation task queued for CommsAgent.",
    approvalRequired: false,
    handoffChain: ["InvoiceAgent", "CommsAgent"],
    evidence: ["Approval k175j7...", "Reimbursement marked", "Tenant contact record"],
    related: ["Invoice j97byg...", "Comms task jx70g..."],
    audit: ["Invoice approved", "Reimbursement marked", "Comms confirmation queued"],
  },
  {
    id: "op-1009",
    agent: "ContractAgent",
    workflowType: "Relisting draft",
    property: "71 Cantonment Close #12-184",
    person: "Maya Chen",
    timestamp: "Fri, 10:30",
    status: "Awaiting approval",
    confidence: 93,
    proposedAction: "Approve copyable relisting draft before manual listing.",
    approvalRequired: true,
    handoffChain: ["ContractAgent", "Human Approval"],
    evidence: ["Lease expiry", "Owner requested relisting", "Draft listing copy"],
    related: ["Relisting draft kx77md...", "Approval k172y..."],
    audit: ["Draft created", "Approval requested"],
  },
  {
    id: "op-1010",
    agent: "CommsAgent",
    workflowType: "WhatsApp reply",
    property: "9 Tanjong Rhu Road #21-11",
    person: "Mei Wong",
    timestamp: "Thu, 18:45",
    status: "Completed",
    confidence: 90,
    proposedAction: "Handoff completed after tenant confirmed job completion.",
    approvalRequired: false,
    handoffChain: ["MaintenanceAgent", "CommsAgent"],
    evidence: ["Tenant WhatsApp reply", "Maintenance task pending verification"],
    related: ["Maintenance verification"],
    audit: ["Reply received", "Task marked done"],
  },
];

export const conversations: Conversation[] = [
  {
    id: "c1",
    contact: "Maya Chen",
    role: "owner",
    channel: "Email",
    property: "71 Cantonment Close #12-184",
    latest: "Wednesday afternoon works for the lease renewal meeting.",
    assignedAgent: "CommsAgent",
    status: "Scheduling",
    humanRequired: false,
    messages: [
      { author: "CommsAgent", body: "Could you share two preferred slots for the renewal discussion?", time: "10:34", kind: "agent" },
      { author: "Maya Chen", body: "Wednesday afternoon works. Please include the manager.", time: "10:46", kind: "inbound" },
    ],
    draftReply: "Thanks Maya. I will hold Wednesday 3:00 PM with the property manager and send a calendar invitation.",
    sourceContext: ["Lease expires 2027-03-31", "ContractAgent requested renewal scheduling", "Manager timezone Asia/Singapore"],
    linkedWorkflow: "schedule_lease_renewal_meeting",
  },
  {
    id: "c2",
    contact: "Priya Menon",
    role: "tenant",
    channel: "WhatsApp",
    property: "71 Cantonment Close #12-184",
    latest: "Thanks, please confirm once reimbursement is processed.",
    assignedAgent: "CommsAgent",
    status: "Ready to send",
    humanRequired: false,
    messages: [
      { author: "Priya Menon", body: "I paid the plumber directly and uploaded the receipt.", time: "09:15", kind: "inbound" },
      { author: "InvoiceAgent", body: "Receipt was approved and marked reimbursed.", time: "09:22", kind: "agent" },
    ],
    draftReply: "Your reimbursement has been marked as processed. Please allow the usual bank processing time.",
    sourceContext: ["Invoice j97byg...", "Approval k175j7...", "Reimbursement completed"],
    linkedWorkflow: "invoice_reimbursement_confirmation",
  },
  {
    id: "c3",
    contact: "CoolAir Services",
    role: "vendor",
    channel: "WhatsApp",
    property: "18 Jervois Road #06-03",
    latest: "Earliest technician slot is tomorrow 11:00.",
    assignedAgent: "CommsAgent",
    status: "Human review required",
    humanRequired: true,
    messages: [
      { author: "CommsAgent", body: "Can you inspect a leaking AC at 18 Jervois Road?", time: "08:40", kind: "agent" },
      { author: "CoolAir Services", body: "Tomorrow 11:00 is available. Estimate SGD 120 inspection.", time: "09:03", kind: "inbound" },
    ],
    draftReply: "Thank you. We are confirming approval and tenant availability before booking.",
    sourceContext: ["Maintenance task AC leak", "Vendor approved list", "Inspection estimate SGD 120"],
    linkedWorkflow: "maintenance_vendor_scheduling",
  },
  {
    id: "c4",
    contact: "Adrian Lim",
    role: "owner",
    channel: "Email",
    property: "18 Jervois Road #06-04",
    latest: "Please send the reimbursement details before approval.",
    assignedAgent: "InvoiceAgent",
    status: "Awaiting approval",
    humanRequired: true,
    messages: [{ author: "Adrian Lim", body: "Please send the reimbursement details before approval.", time: "Yesterday", kind: "inbound" }],
    draftReply: "Attached is the extracted invoice summary and source receipt for your review.",
    sourceContext: ["Receipt OCR confidence 62%", "Amount SGD 284.60", "Tenant Hafiz Rahman"],
    linkedWorkflow: "invoice_claim_review",
  },
  {
    id: "c5",
    contact: "Nora Tan",
    role: "tenant",
    channel: "WhatsApp",
    property: "18 Jervois Road #06-03",
    latest: "The AC leak is worse now.",
    assignedAgent: "MaintenanceAgent",
    status: "SLA at risk",
    humanRequired: false,
    messages: [{ author: "Nora Tan", body: "The AC leak is worse now.", time: "Yesterday", kind: "inbound" }],
    draftReply: "A technician slot is being coordinated. We will confirm once the vendor and approval are aligned.",
    sourceContext: ["Maintenance priority high", "Vendor availability pending", "SLA due today"],
    linkedWorkflow: "maintenance_ac_leak",
  },
  {
    id: "c6",
    contact: "Sophia Ong",
    role: "owner",
    channel: "Voice",
    property: "9 Tanjong Rhu Road #21-10",
    latest: "Call transcript confirms renewal terms discussion.",
    assignedAgent: "CommsAgent",
    status: "Completed",
    humanRequired: false,
    messages: [{ author: "CommsAgent", body: "Voice call summary: owner accepted renewal discussion agenda.", time: "Mon", kind: "agent" }],
    draftReply: "No reply needed.",
    sourceContext: ["Call transcript", "Calendar event created"],
    linkedWorkflow: "lease_renewal_meeting",
  },
  {
    id: "c7",
    contact: "BrightPlumb",
    role: "vendor",
    channel: "Email",
    property: "71 Cantonment Close #12-185",
    latest: "Invoice sent after pipe replacement.",
    assignedAgent: "InvoiceAgent",
    status: "Document received",
    humanRequired: false,
    messages: [{ author: "BrightPlumb", body: "Invoice attached for completed pipe replacement.", time: "Fri", kind: "inbound" }],
    draftReply: "Received. The invoice will be matched to the maintenance job and routed for approval.",
    sourceContext: ["Maintenance completed", "Contractor receipt"],
    linkedWorkflow: "contractor_invoice",
  },
  {
    id: "c8",
    contact: "Mei Wong",
    role: "tenant",
    channel: "WhatsApp",
    property: "9 Tanjong Rhu Road #21-11",
    latest: "Everything is working now.",
    assignedAgent: "CommsAgent",
    status: "Closed",
    humanRequired: false,
    messages: [{ author: "Mei Wong", body: "Everything is working now.", time: "Thu", kind: "inbound" }],
    draftReply: "Thank you for confirming. The maintenance task has been closed.",
    sourceContext: ["Post-job verification", "Maintenance completed"],
    linkedWorkflow: "maintenance_verification",
  },
];

export const approvals: Approval[] = [
  { id: "a1", action: "Approve vendor scheduling", agent: "MaintenanceAgent", reason: "Vendor has proposed an inspection slot and estimate.", evidence: ["Vendor reply", "Tenant availability", "Approved vendor list"], property: "18 Jervois Road #06-03", person: "Nora Tan", risk: "Medium", deadline: "Today 18:00", status: "Pending" },
  { id: "a2", action: "Approve tenant notice", agent: "CommsAgent", reason: "Sensitive lease-renewal message prepared for owner and tenant.", evidence: ["Lease expiry", "Draft notice", "Owner contact"], property: "71 Cantonment Close #12-184", person: "Maya Chen", risk: "Medium", deadline: "Tomorrow 12:00", status: "Pending" },
  { id: "a3", action: "Approve owner reimbursement", agent: "InvoiceAgent", reason: "Tenant submitted paid receipt for maintenance reimbursement.", evidence: ["Receipt image", "OCR fields", "Task link"], property: "18 Jervois Road #06-04", person: "Hafiz Rahman", risk: "High", deadline: "2 days", status: "Pending" },
  { id: "a4", action: "Approve lease relisting", agent: "ContractAgent", reason: "Owner requested manual listing after renewal declined.", evidence: ["Relisting draft", "Lease expiry", "Owner instruction"], property: "71 Cantonment Close #12-184", person: "Maya Chen", risk: "High", deadline: "3 days", status: "Pending" },
  { id: "a5", action: "Approve invoice claim", agent: "InvoiceAgent", reason: "OCR confidence low and amount needs review.", evidence: ["Blurred receipt", "Extracted SGD 284.60", "Tenant message"], property: "18 Jervois Road #06-04", person: "Hafiz Rahman", risk: "Medium", deadline: "Today 17:00", status: "Pending" },
];

export const documents: DocumentSource[] = [
  { id: "d1", category: "Lease PDFs", fileName: "cantonment_lease_2026.pdf", linkedEntity: "71 Cantonment Close #12-184 / Priya Menon", uploadedAt: "May 9", extractedStatus: "Completed", confidence: 100, relatedAgent: "ContractAgent", reviewStatus: "Confirmed", fields: { startDate: "2026-04-01", endDate: "2027-03-31", rent: "SGD 2,450", tenant: "Priya Menon" } },
  { id: "d2", category: "Invoice PDFs/images", fileName: "premier_maintenance_receipt.png", linkedEntity: "71 Cantonment Close #12-184 / Priya Menon", uploadedAt: "May 9", extractedStatus: "Completed", confidence: 98, relatedAgent: "InvoiceAgent", reviewStatus: "Approved", fields: { vendor: "Premier Maintenance", amount: "USD 1,105.30", date: "2025-02-21", category: "Maintenance & Repairs" } },
  { id: "d3", category: "Invoice PDFs/images", fileName: "ac_repair_blur_041.png", linkedEntity: "18 Jervois Road #06-04 / Hafiz Rahman", uploadedAt: "May 8", extractedStatus: "Needs review", confidence: 62, relatedAgent: "InvoiceAgent", reviewStatus: "Human review required", fields: { vendor: "Unclear", amount: "SGD 284.60", date: "Unreadable" } },
  { id: "d4", category: "Property photos", fileName: "tanjong_rhu_living_room.jpg", linkedEntity: "9 Tanjong Rhu Road #21-10", uploadedAt: "May 7", extractedStatus: "Ready", confidence: 95, relatedAgent: "ContractAgent", reviewStatus: "Ready for relisting draft", fields: { room: "Living room", listingUse: "Yes" } },
  { id: "d5", category: "Tenant correspondence", fileName: "nora_ac_leak_thread.eml", linkedEntity: "18 Jervois Road #06-03 / Nora Tan", uploadedAt: "May 7", extractedStatus: "Completed", confidence: 88, relatedAgent: "MaintenanceAgent", reviewStatus: "Linked to task", fields: { issue: "AC leak", priority: "High" } },
  { id: "d6", category: "Owner documents", fileName: "maya_renewal_instruction.pdf", linkedEntity: "71 Cantonment Close #12-184 / Maya Chen", uploadedAt: "May 6", extractedStatus: "Completed", confidence: 91, relatedAgent: "ContractAgent", reviewStatus: "Source evidence attached", fields: { instruction: "Discuss renewal", rentTarget: "SGD 2,600" } },
  { id: "d7", category: "Contractor receipts", fileName: "brightplumb_invoice_559.pdf", linkedEntity: "71 Cantonment Close #12-185 / BrightPlumb", uploadedAt: "May 5", extractedStatus: "Processing", confidence: 74, relatedAgent: "InvoiceAgent", reviewStatus: "Pending extraction", fields: { vendor: "BrightPlumb", type: "Pipe replacement" } },
  { id: "d8", category: "Lease PDFs", fileName: "jervois_lease_2025.pdf", linkedEntity: "18 Jervois Road #06-03 / Nora Tan", uploadedAt: "May 4", extractedStatus: "Completed", confidence: 96, relatedAgent: "ContractAgent", reviewStatus: "Confirmed", fields: { endDate: "2027-09-30", rent: "SGD 3,200" } },
];

export const agents: AgentRecord[] = [
  { name: "OrchestratorAgent", responsibility: "Classifies events, loads context, and routes handoffs.", activeTasks: 3, toolScope: ["Convex context lookup", "Agent handoff"], approvalRequirements: ["No business side effects"], recentHandoffs: ["InvoiceAgent", "ContractAgent", "MaintenanceAgent"], errorCount: 0, lastRun: "4 min ago" },
  { name: "MaintenanceAgent", responsibility: "Coordinates maintenance workflows and vendor selection.", activeTasks: 5, toolScope: ["Vendor lookup", "Task updates", "Comms task queue"], approvalRequirements: ["Vendor scheduling", "Cost-impacting actions"], recentHandoffs: ["CommsAgent", "Human Approval"], errorCount: 1, lastRun: "12 min ago" },
  { name: "ContractAgent", responsibility: "Extracts leases, monitors expiries, creates relisting drafts.", activeTasks: 4, toolScope: ["Lease extraction", "Expiry cron", "Relisting drafts", "Comms task queue"], approvalRequirements: ["Lease extraction review", "Relisting approval"], recentHandoffs: ["CommsAgent", "Human Approval"], errorCount: 0, lastRun: "18 min ago" },
  { name: "CommsAgent", responsibility: "Owns WhatsApp, email, voice, availability polling, reminders, and calendar scheduling.", activeTasks: 7, toolScope: ["WhatsApp", "Email", "Voice", "Google Calendar", "Conversation records"], approvalRequirements: ["Sensitive outbound messages"], recentHandoffs: ["Human Approval", "MaintenanceAgent", "ContractAgent"], errorCount: 0, lastRun: "2 min ago" },
  { name: "InvoiceAgent", responsibility: "Extracts receipts, creates claims, routes approvals, queues confirmations.", activeTasks: 4, toolScope: ["Receipt OCR", "Invoice records", "Approvals", "Comms task queue"], approvalRequirements: ["Reimbursement approval", "Low confidence OCR"], recentHandoffs: ["CommsAgent", "Human Approval"], errorCount: 2, lastRun: "8 min ago" },
];

export const auditLogs: AuditLogEntry[] = Array.from({ length: 20 }, (_, index) => {
  const op = operations[index % operations.length];
  const risks: AuditLogEntry["risk"][] = ["Low", "Medium", "High"];
  return {
    id: `log-${index + 1}`,
    timestamp: `May ${9 - Math.floor(index / 4)}, ${String(10 + (index % 8)).padStart(2, "0")}:${index % 2 ? "45" : "12"}`,
    actor: index % 5 === 0 ? "Human: Tanvi" : op.agent,
    action: op.audit[index % op.audit.length],
    target: op.workflowType,
    source: index % 3 === 0 ? "dashboard" : index % 3 === 1 ? "email" : "cron",
    approvalRef: op.approvalRequired ? `approval-${1000 + index}` : "-",
    status: op.status,
    risk: risks[index % risks.length],
    agent: index % 5 === 0 ? "Human" : op.agent,
    property: op.property,
    entityType: index % 2 === 0 ? "task" : "message",
  };
});

export const analytics = [
  { label: "Avg maintenance resolution", value: "1.8 days", delta: "12% faster" },
  { label: "Approval turnaround", value: "3.4 hrs", delta: "SLA healthy" },
  { label: "Agent success rate", value: "96.2%", delta: "5 agents online" },
  { label: "OCR confidence avg", value: "88%", delta: "2 low-confidence docs" },
  { label: "SLA breaches", value: "1", delta: "AC leak at risk" },
  { label: "Conversation response time", value: "9 min", delta: "WhatsApp fastest" },
  { label: "Lease expiry pipeline", value: "4", delta: "2 need scheduling" },
  { label: "Invoice claim volume", value: "12", delta: "5 pending review" },
];
